# syntax = docker/dockerfile:1.2

## Start the definition of our build stage
FROM golang:1-alpine
RUN echo "test Dockerfile.init"

RUN apk update && \
    apk add --no-cache \
    bash \
    pkgconfig \
    gcc \
    libc-dev \
    libxml2-dev \
    postgresql-client \
    git

RUN go install github.com/rubenv/sql-migrate/...

COPY migrations /migrations
WORKDIR /migrations

ENV CUSTOMER_DATABASE_HOST=postgres

CMD /go/bin/sql-migrate up -env="local"
